server:
  port: 8085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.113.141:8848
    alibaba:
      seata:
        tx-service-group: gmall-sms-seata
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.113.141:3306/guli_sms
    username: root
    password: root
# redis
  redis:
    host: 122.51.113.141
    port: 6379

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/sms/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# seata config
seata:
  tx-service-group: gmall-sms-seata
  client:
    support:
      spring:
        datasource-autoproxy: true
  config:
    type: nacos
    nacos:
      server-addr: 122.51.113.141:8848
  registry:
    type: nacos
    nacos:
      server-addr: 122.51.113.141:8848
  service:
    grouplist: 121.36.130.137:8091