server:
  port: 8888

# 网关配置
spring:
  cloud:
    gateway:
      #路由
      routes:
        - id: pms-route # 路由的ID
          uri: lb://pms-service #lb 代表从注册中心获取服务  //pms-service  是我们注册中心配置的服务名称
          predicates: #配置该路由的断言，通过PredicateDefinition类进行接收配置。
            - Path=/pms/** # 转发该路径
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
    # nacos配置
    nacos:
      discovery:
        server-addr: 122.51.113.141:8848
  application:
    name: gmall-gateway