server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.113.141:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.113.141:3306/guli_pms
    username: root
    password: root

  redis:
    host: 122.51.113.141
    port: 6379
