server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.113.141:8848
    alibaba:
      seata:
        tx-service-group: gmall-pms-seata

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.113.141:3306/guli_pms
    username: root
    password: root
# redis
  redis:
    host: 122.51.113.141
    port: 6379

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/pms/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# seata config
seata:
  tx-service-group: gmall-pms-seata
  client:
    support:
      spring:
        datasource-autoproxy: true
    rm:
      lock:
        lock-retry-times: 60
  config:
    type: nacos
    nacos:
      server-addr: 122.51.113.141:8848
  registry:
    type: nacos
    nacos:
      server-addr: 122.51.113.141:8848
  service:
    grouplist: 121.36.130.137:8091
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000 # 连接超时
        readTimeout: 600000 # 响应超时
### Ribbon 配置
ribbon:
  # 连接超时
  ConnectTimeout: 2000
  # 响应超时
  ReadTimeout: 5000
#配置熔断的时间监听
hystrix:
  command:
    default:
      execution:
        timeout:
          isolation:
            thread:
              timeoutInMilliseconds: 10000
          enabled: false