server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.113.141:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.113.141:3306/guli_wms
    username: root
    password: root
# redis
  redis:
    host: 122.51.113.141
    port: 6379

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/wms/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl